## Question 9: Numerical Differentiation Using Interpolation

Write a Python program that accepts the following equally spaced data:

| X | 0 | 1 | 2 | 3 | 4 |
|---|---|---|---|---|---|
| Y | 1 | 3 | 7 | 13 | 21 |

The program should:

1. Construct the forward difference table.
2. Compute the first derivative f'(1) using Newton's Forward Difference Formula.
3. Construct the backward difference table.
4. Compute the first derivative f'(4) using Newton's Backward Difference Formula.
5. Compute the second derivative at the required point using the appropriate interpolation formula.
6. Display all intermediate difference tables and the numerical values of the derivatives.

In [1]:
import numpy as np
import pandas as pd

In [2]:
#inititalising the actual value
x=np.array([0,1,2,3,4],dtype=float)
y=np.array([1,3,7,13,21],dtype=float)

1) To create the forward difference table we take the value or accept the value then we knoe:<br>
Forward difference=y<sub>n+1</sub>-y<sub>n</sub><br>
We know that at each difference we reduce by 1 so we consider y we exactly construct 2d matrix to represent the forward difference.

In [5]:
def find_forward_diff(x,y)->np.ndarray:
    #this should give list forward differences
    n=len(x) #getting the length 
    forward=np.zeros((n,n))
    forward[:,0]=y #setting value of y
    #now calculating all the values of the forward difference below
    k=n
    for i in range(1,n): # as said above we know we get difference till the length of the dependent variable here
        #now for each of the delta
        for j in range(0,k-1):
            forward[j,i]=forward[j+1,i-1]-forward[j,i-1]
        k-=1
    print(forward)

find_forward_diff(x,y)
            
    


[[ 1.  2.  2.  0.  0.]
 [ 3.  4.  2.  0.  0.]
 [ 7.  6.  2.  0.  0.]
 [13.  8.  0.  0.  0.]
 [21.  0.  0.  0.  0.]]
